server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-alias: appstore
    enabled: true
  http:
    port: 8080
spring:
  application:
    name: reto_PSP_APK